[package]
name = "abs_tree"
version = "0.1.0"
edition = "2021"

[dependencies]
itertools = "0.10.0"
maplit = "1.0.2"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.70"
rand = "0.8.5"